# Generated by Django 2.0.4 on 2018-04-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megamaninn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
