# Generated by Django 2.0.4 on 2018-04-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megamaninn', '0002_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
