# Generated by Django 2.0.4 on 2018-04-22 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('megamaninn', '0003_auto_20180422_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profilePicture',
        ),
    ]
