# Generated by Django 2.0.4 on 2018-04-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megamaninn', '0003_room_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
