# Generated by Django 2.0.4 on 2018-04-23 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('megamaninn', '0005_auto_20180423_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.CharField(help_text='Enter comments', max_length=100)),
                ('rating', models.PositiveIntegerField()),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='megamaninn.profile')),
            ],
        ),
    ]
