# Generated by Django 2.0.4 on 2018-04-29 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('megamaninn', '0006_booking_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='spa_service',
            new_name='laundry_service',
        ),
    ]
